/** Declaration file generated by dts-gen */

export const attributes: {
    path: string;
};

export function get(name: any, ...args: any[]): any;

export function remove(name: any, attributes: any): void;

export function set(name: any, value: any, attributes: any): any;

export function withAttributes(attributes: any): any;

export function withConverter(converter: any): any;

export namespace converter {
    function read(value: any): any;

    function write(value: any): any;

}

